name:                differential-datalog-ovsdb
version:             0.1.0.0
github:              "ryzhyk/differential-datalog"
license:             BSD3
author:              "Leonid Ryzhyk"
maintainer:          "lryzhyk@vmware.com"
copyright:           "VMware, Inc"

# Metadata used when publishing your package
# synopsis:            OVSDB adapter for differential datalog
# category:            Language

description:         OVSDB adapter for differential datalog

dependencies:
- base >= 4.7 && < 5
- parsec
- pretty
- differential-datalog
- containers
- raw-strings-qq
- mtl

library:
  source-dirs: src
executables:
  ovsdb2ddlog:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - differential-datalog
    - differential-datalog-ovsdb
    - filepath
    - containers

tests:
  differential-datalog-ovsdb-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - differential-datalog
    - differential-datalog-ovsdb
    - tasty
    - HUnit
    - tasty-golden
    - filepath
