name:                differential-datalog
version:             0.1.0.0
github:              "ryzhyk/differential-datalog"
license:             BSD3
author:              "Leonid Ryzhyk"
maintainer:          "lryzhyk@vmware.com"
copyright:           "VMware, Inc"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Incremental Datalog engine based on differential dataflow
# category:            Language

description:         Please see the README on Github at <https://github.com/ryzhyk/differential-datalog#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- parsec
- pretty
- directory
- containers
- binary
- bytestring
- fgl
- split
- MissingH
- raw-strings-qq
- tuple
- file-embed
- filepath
- wide-word
- graphviz
- text
- githash
- process

library:
  source-dirs: src
  ghc-options:
  - -optl-static
  - -optl-pthread
  - -Wall
  - -Werror
executables:
  ddlog:
    main:                Main.hs
    source-dirs:         app
    # Mac OS does not support statically linked executables.
    when:
    - condition: os(linux)
      then:
          ghc-options:
              - -threaded
              - -rtsopts
              - -with-rtsopts=-N
              - -optl-static
              - -optl-pthread
              - -Wall
              - -Werror
      else:
          ghc-options:
              - -threaded
              - -rtsopts
              - -with-rtsopts=-N
              - -Wall
              - -Werror
    dependencies:
    - differential-datalog
    - filepath
  ovsdb2ddlog:
    main:                Main.hs
    source-dirs:         adapters/ovsdb
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - differential-datalog
    - filepath
    - containers

tests:
  differential-datalog-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - differential-datalog
    - tasty
    - HUnit
    - tasty-golden
    - filepath
    - deepseq
    - zlib
