import intern

input relation BI(b: bool)
input relation CI(c: bit<32>)
input relation DI(d: signed<16>)
input relation EI(e: bigint)
output relation EO(e: bigint)
input relation FI(s: string)
input relation GI(d: bit<64>)
input relation HI(d: bit<128>)
input relation II(d: bit<12>)
typedef tuple = (bool, bit<8>, string)
input relation JI(a: (bool, bit<8>, string))
input relation KI(t: tuple)
input relation LI[tuple]
input relation L0I(a: bool, b: bit<8>, s: string) primary key (x) x.a
input relation MI(v: Vec<bool>)
input relation NI(v: Vec<tuple>)
input relation OI(v: Vec<Vec<bool>>)
input relation PI1(s: Set<bit<8>>)
input relation PI2(s: Set<bit<16>>)
input relation PI3(s: Set<bit<32>>)
input relation PI4(s: Set<bit<64>>)
input relation PI5(s: Set<bit<128>>)
input relation QI(m: Map<bit<32>, string>)
input relation RI(m: Ref<bit<32>>)
typedef C = C{x: string}
input relation SI(m: C)
input relation TI(m: Option<bit<32>>)
typedef Many = A{x: string}
             | B{b: bool}
             | D{t: tuple}
input relation UI[Many]
input relation VI(a: bool, b: Many)
input relation WI(m: Option<Many>)
input relation XI(m: Vec<Many>)
typedef VOT = Vec<Option<tuple>>
input relation YI(v: VOT)
input relation ZI(d: bit<256>)
input relation ZI0[string]
input relation ZI1[bool]
input relation ZI2[bit<32>]
input relation ZI3[Many]
input relation ZI4[Vec<string>]
input relation ZI5[Map<string, Many>]
input relation ZI6[Option<string>]
input relation ZI7[Ref<string>]
input relation ZI8[Ref<bit<25>>]
input relation ZI9[Ref<Ref<bit<25>>>]
input relation ZI10[Ref<IString>]
input relation ZI11[Map<Many, string>]
input relation ZI12[(string, bigint, Vec<bigint>, (bit<16>, Many))]
typedef Generic<'A, 'B> = Generic{f0: string, f1: 'A, f2: 'B}
input relation ZI13[Generic<Ref<tuple>, Many>]
typedef Cases<'A, 'B> = First{a: 'A}
                      | Second{b: 'B}
input relation ZI14(c: Cases<string, signed<32>>)
typedef F<'A> = FirstF{a: 'A}
typedef S<'A> = SecondS{a: 'A}
typedef Or<'A, 'B> = OrFirst{f: F<'A>}
                   | OrSecond{s: S<'B>}
input relation ZI15(c: Or<string, signed<32>>)
import module
input relation ZI20(t: mtuple)
input relation ZI21(m: bit<32>) primary key (r) r.m
