/*
 * FlatBuffers-based serialization API test.
 *
 * Perform the same set of updates twice, once using the DDlogRecord-based
 * commit method, and once using FlatBuffers-based commit.  Write updates to
 * two different files that can be diffed by the test script.
 */

import java.io.IOException;
import java.util.*;
import java.lang.RuntimeException;
import java.math.BigInteger;
import java.util.Arrays;
import java.io.PrintStream;
import java.io.UncheckedIOException;

/* Generic DDlog API shared by all programs. */
import ddlogapi.DDlogAPI;
import ddlogapi.DDlogCommand;
import ddlogapi.DDlogException;

/* Additional program-specific bindings generated by `ddlog`. */
import ddlog.flatbufTest.*;

public class Test {
    private final DDlogAPI api;
    private final PrintStream fb_file;
    private final PrintStream rec_file;

    Test() throws IOException, DDlogException {
        /* Create an instance of the DDlog program with one worker thread. */
        this.api = new DDlogAPI(1, null, false);
        api.recordCommands("replay.dat", false);

        this.fb_file  = new PrintStream("fb.dump");
        this.rec_file = new PrintStream("rec.dump");
    }

    // typedef tuple = (bool, bit<8>, string)
    private String printTuple(Tuple3__bool__bit_8___stringReader t) {
        return "(" + t.a0() + ", " + t.a1() + ", \"" + t.a2() + "\")";
    }

    // typedef Many = A{x: string}
    //              | B{b: bool}
    //              | D{t: tuple}
    private String printMany(ManyReader m) {
        if (m instanceof ManyReader.A) {
            return "A{\"" + ((ManyReader.A)m).x() + "\"}";
        } else if (m instanceof ManyReader.B) {
            return "B{" + ((ManyReader.B)m).b() + "}";
        } else if (m instanceof ManyReader.D) {
            return "D{" + printTuple(((ManyReader.D)m).t()) + "}";
        } else {
            throw new IllegalArgumentException("Invalid Many value " + m.toString());
        }
    }

    private String printCases(String relname, Cases__string__signed_32_Reader r) {
        if (r instanceof Cases__string__signed_32_Reader.First) {
            return relname + "{First{\"" + ((Cases__string__signed_32_Reader.First)r).a() + "\"}}";
        } else if (r instanceof Cases__string__signed_32_Reader.Second) {
            return relname + "{Second{" + ((Cases__string__signed_32_Reader.Second)r).b() + "}}";
        } else {
            throw new IllegalArgumentException("Invalid Cases value " + r.toString());
        }
    }

    private String printOr(String relname, Or__string__signed_32_Reader r) {
        if (r instanceof Or__string__signed_32_Reader.OrFirst) {
            return relname + "{OrFirst{F{\"" + ((Or__string__signed_32_Reader.OrFirst)r).f().a() + "\"}}}";
        } else if (r instanceof Or__string__signed_32_Reader.OrSecond) {
            return relname + "{OrSecond{S{" + ((Or__string__signed_32_Reader.OrSecond)r).s().a() + "}}}";
        } else {
            throw new IllegalArgumentException("Invalid Cases value " + r.toString());
        }
    }

    void onRecCommit(DDlogCommand command) throws IOException {
        rec_file.println(command.toString());
    }

    void onFBCommit(DDlogCommand<Object> command) throws IOException {
        int relid = command.relid();
        switch (relid) {
            /*
            case flatbutTestRelation.AO: {
                // TODO
                AOreader a = (AOreader)command.value();
                fb_file.println("From " + relid + " " + command.kind() + "AO[" + v + "]");
                break;
            }
            */
            // output relation BO(b: bool)
            case flatbufTestRelation.BO: {
                BOReader v = (BOReader)command.value();
                fb_file.println("From " + relid + " " + command.kind() + " BO{" + v.b() + "}");
                break;
            }

            // output relation CO(c: bit<32>)
            case flatbufTestRelation.CO: {
                COReader v = (COReader)command.value();
                fb_file.println("From " + relid + " " + command.kind() + " CO{" + v.c() + "}");
                break;
            }

            // output relation DO(d: signed<16>)
            case flatbufTestRelation.DO: {
                DOReader v = (DOReader)command.value();
                fb_file.println("From " + relid + " " + command.kind() + " DO{" + v.d() + "}");
                break;
            }

            // output relation EO(e: bigint)
            case flatbufTestRelation.EO: {
                EOReader v = (EOReader)command.value();
                fb_file.println("From " + relid + " " + command.kind() + " EO{" + v.e() + "}");
                break;
            }

            // output relation FO(s: string)
            case flatbufTestRelation.FO: {
                FOReader v = (FOReader)command.value();
                fb_file.println("From " + relid + " " + command.kind() + " FO{\"" + v.s() + "\"}");
                break;
            }

            // output relation GO(d: bit<64>)
            case flatbufTestRelation.GO: {
                GOReader v = (GOReader)command.value();
                fb_file.println("From " + relid + " " + command.kind() + " GO{" + v.d() + "}");
                break;
            }

            // output relation HO(d: bit<128>)
            case flatbufTestRelation.HO: {
                HOReader v = (HOReader)command.value();
                fb_file.println("From " + relid + " " + command.kind() + " HO{" + v.d() + "}");
                break;
            }

            // output relation IO(d: bit<12>)
            case flatbufTestRelation.IO: {
                IOReader v = (IOReader)command.value();
                fb_file.println("From " + relid + " " + command.kind() + " IO{" + v.d() + "}");
                break;
            }

            // output relation JO(a: (bool, bit<8>, string))
            case flatbufTestRelation.JO: {
                JOReader v = (JOReader)command.value();
                Tuple3__bool__bit_8___stringReader a = v.a();
                fb_file.println("From " + relid + " " + command.kind() + " JO{" + printTuple(a) + "}");
                break;
            }

            // output relation KO(t: tuple)
            case flatbufTestRelation.KO: {
                KOReader v = (KOReader)command.value();
                Tuple3__bool__bit_8___stringReader t = v.t();
                fb_file.println("From " + relid + " " + command.kind() + " KO{" + printTuple(t) + "}");
                break;
            }

            // output relation LO[tuple]
            case flatbufTestRelation.LO: {
                Tuple3__bool__bit_8___stringReader v = (Tuple3__bool__bit_8___stringReader)command.value();
                fb_file.println("From " + relid + " " + command.kind() + " " + printTuple(v));
                break;
            }

            // output relation L0O(a: bool, b: bit<8>, s: string)
            case flatbufTestRelation.L0O: {
                L0OReader v = (L0OReader)command.value();
                fb_file.println("From " + relid + " " + command.kind() + " L0O{" + v.a() + "," + v.b() + ",\"" + v.s() + "\"}");
                break;
            }

            // output relation MO(v: Vec<bool>)
            case flatbufTestRelation.MO: {
                MOReader v = (MOReader)command.value();
                fb_file.println("From " + relid + " " + command.kind() + " MO{" + v.v() + "}");
                break;
            }

            // output relation NO(v: Vec<tuple>)
            case flatbufTestRelation.NO: {
                NOReader v = (NOReader)command.value();
                List<Tuple3__bool__bit_8___stringReader> vs = v.v();
                ArrayList<String> strings = new ArrayList<String>(vs.size());
                vs.forEach((t) -> strings.add(printTuple(t)));
                fb_file.println("From " + relid + " " + command.kind() + " NO{[" + String.join(", ",strings) + "]}");
                break;
            }

            // output relation OO(v: Vec<Vec<bool>>)
            case flatbufTestRelation.OO: {
                OOReader v = (OOReader)command.value();
                List<List<Boolean>> vs = v.v();
                fb_file.println("From " + relid + " " + command.kind() + " OO{" + vs + "}");
                break;
            }

            // output relation PO1(s: Set<bit<8>>)
            case flatbufTestRelation.PO1: {
                PO1Reader v = (PO1Reader)command.value();
                List<Integer> vs = v.s();
                fb_file.println("From " + relid + " " + command.kind() + " PO1{" + vs + "}");
                break;
            }

            // output relation PO2(s: Set<bit<16>>)
            case flatbufTestRelation.PO2: {
                PO2Reader v = (PO2Reader)command.value();
                List<Integer> vs = v.s();
                fb_file.println("From " + relid + " " + command.kind() + " PO2{" + vs + "}");
                break;
            }

            // output relation PO3(s: Set<bit<32>>)
            case flatbufTestRelation.PO3: {
                PO3Reader v = (PO3Reader)command.value();
                List<Long> vs = v.s();
                fb_file.println("From " + relid + " " + command.kind() + " PO3{" + vs + "}");
                break;
            }

            // output relation PO4(s: Set<bit<64>>)
            case flatbufTestRelation.PO4: {
                PO4Reader v = (PO4Reader)command.value();
                List<Long> vs = v.s();
                fb_file.println("From " + relid + " " + command.kind() + " PO4{" + vs + "}");
                break;
            }

            // output relation PO5(s: Set<bit<128>>)
            case flatbufTestRelation.PO5: {
                PO5Reader v = (PO5Reader)command.value();
                List<BigInteger> vs = v.s();
                fb_file.println("From " + relid + " " + command.kind() + " PO5{" + vs + "}");
                break;
            }

            // output relation QO(m: Map<bit<32>, string>)
            case flatbufTestRelation.QO: {
                QOReader v = (QOReader)command.value();
                Map<Long,String> vs = v.m();
                ArrayList<String> vs_strs = new ArrayList<String>(vs.size());
                for (Map.Entry<Long,String> entry : vs.entrySet()) {
                    vs_strs.add(entry.getKey() + "=>\"" + entry.getValue() + "\"");
                }
                fb_file.println("From " + relid + " " + command.kind() + " QO{{" + String.join(", ", vs_strs) + "}}");
                break;
            }

            // output relation RO(m: Ref<bit<32>>)
            case flatbufTestRelation.RO: {
                ROReader v = (ROReader)command.value();
                fb_file.println("From " + relid + " " + command.kind() + " RO{" + v.m() + "}");
                break;
            }

            // output relation SO(m: C)
            case flatbufTestRelation.SO: {
                SOReader v = (SOReader)command.value();
                fb_file.println("From " + relid + " " + command.kind() + " SO{C{\"" + v.m().x() + "\"}}");
                break;
            }

            // output relation TO(m: Option<bit<32>>)
            case flatbufTestRelation.TO: {
                std_Option__bit_32_Reader m = (std_Option__bit_32_Reader)((TOReader)command.value()).m();
                if (m instanceof std_Option__bit_32_Reader.std_Some) {
                    fb_file.println("From " + relid + " " + command.kind() +
                            " TO{std_Some{" + ((std_Option__bit_32_Reader.std_Some)m).x() + "}}");
                } else {
                    fb_file.println("From " + relid + " " + command.kind() + " TO{std_None{}}");
                }
                break;
            }

            // output relation UO[Many]
            case flatbufTestRelation.UO: {
                ManyReader m = (ManyReader)command.value();
                fb_file.println("From " + relid + " " + command.kind() + " " + printMany(m));
                break;
            }

            //output relation VO(a: bool, b: Many)
            case flatbufTestRelation.VO: {
                VOReader v = (VOReader)command.value();
                fb_file.println("From " + relid + " " + command.kind() + " VO{" + v.a() + "," + printMany(v.b()) + "}");
                break;
            }

            // output relation WO(m: Option<Many>)
            case flatbufTestRelation.WO: {
                std_Option__ManyReader m = (std_Option__ManyReader)((WOReader)command.value()).m();
                if (m instanceof std_Option__ManyReader.std_Some) {
                    fb_file.println("From " + relid + " " + command.kind() +
                            " WO{std_Some{" + printMany(((std_Option__ManyReader.std_Some)m).x()) + "}}");
                } else {
                    fb_file.println("From " + relid + " " + command.kind() + " WO{std_None{}}");
                }
                break;
            }

            //output relation XO(m: Vec<Many>)
            case flatbufTestRelation.XO: {
                List<ManyReader> m = ((XOReader)command.value()).m();
                ArrayList<String> strings = new ArrayList<String>(m.size());
                m.forEach((x) -> strings.add(printMany(x)));
                fb_file.println("From " + relid + " " + command.kind() + " XO{[" + String.join(", ",strings) + "]}");
                break;
            }

            //typedef VOT = Vec<Option<tuple>>
            // output relation YO(v: VOT)
            case flatbufTestRelation.YO: {
                List<std_Option___bool__bit_8___string_Reader> v = ((YOReader)command.value()).v();
                ArrayList<String> strings = new ArrayList<String>(v.size());
                v.forEach((x) -> {
                    if (x instanceof std_Option___bool__bit_8___string_Reader.std_Some) {
                        strings.add("std_Some{" + printTuple(((std_Option___bool__bit_8___string_Reader.std_Some)x).x()) + "}");
                    } else {
                        strings.add("std_None{}");
                    }
                });
                fb_file.println("From " + relid + " " + command.kind() + " YO{[" + String.join(", ", strings) + "]}");
                break;
            }
            // output relation ZO0[string]
            case flatbufTestRelation.ZO0: {
                String v = (String)command.value();
                fb_file.println("From " + relid + " " + command.kind() + " \"" + v + "\"");
                break;
            }
            // output relation ZO1[bool]
            case flatbufTestRelation.ZO1: {
                Boolean v = (Boolean)command.value();
                fb_file.println("From " + relid + " " + command.kind() + " " + v);
                break;
            }
            // output relation ZO2[bit<32>]
            case flatbufTestRelation.ZO2: {
                Long v = (Long)command.value();
                fb_file.println("From " + relid + " " + command.kind() + " " + v);
                break;
            }
            // output relation ZO3[Many]
            case flatbufTestRelation.ZO3: {
                ManyReader v = (ManyReader)command.value();
                fb_file.println("From " + relid + " " + command.kind() + " " + printMany(v));
                break;
            }
            // output relation ZO4[Vec<string>]
            case flatbufTestRelation.ZO4: {
                @SuppressWarnings("unchecked")
                List<String> v = (List<String>)command.value();
                List<String> quoted = new ArrayList<String>();
                v.forEach((x) -> quoted.add("\"" + x + "\""));
                fb_file.println("From " + relid + " " + command.kind() + " " + quoted);
                break;
            }
            // output relation ZO5[Map<string, Many>]
            case flatbufTestRelation.ZO5: {
                @SuppressWarnings("unchecked")
                Map<String, ManyReader> v = (Map<String, ManyReader>)command.value();
                ArrayList<String> strings = new ArrayList<String>(v.size());
                for (Map.Entry<String, ManyReader> e: v.entrySet()) {
                    strings.add("\"" + e.getKey() + "\"=>" + printMany(e.getValue()));
                }
                fb_file.println("From " + relid + " " + command.kind() + " {" + String.join(", ", strings) + "}");
                break;
            }
            // output relation ZO6[Option<string>]
            case flatbufTestRelation.ZO6: {
                Object v = command.value();
                String s = "";
                if (v instanceof std_Option__stringReader.std_Some) {
                    s = "std_Some{\"" + ((std_Option__stringReader.std_Some)v).x() + "\"}";
                } else {
                    s = "std_None{}";
                }
                fb_file.println("From " + relid + " " + command.kind() + " " + s);
                break;
            }
            // output relation ZO7[Ref<string>]
            case flatbufTestRelation.ZO7: {
                String v = (String)command.value();
                fb_file.println("From " + relid + " " + command.kind() + " \"" + v + "\"");
                break;
            }
            // output relation ZO8[Ref<bit<25>>]
            case flatbufTestRelation.ZO8: {
                Long v = (Long)command.value();
                fb_file.println("From " + relid + " " + command.kind() + " " + v);
                break;
            }
            // output relation ZO9[Ref<Ref<bit<25>>>]
            case flatbufTestRelation.ZO9: {
                Long v = (Long)command.value();
                fb_file.println("From " + relid + " " + command.kind() + " " + v);
                break;
            }
            // output relation ZO10[Ref<IString>]
            case flatbufTestRelation.ZO10: {
                String v = (String)command.value();
                fb_file.println("From " + relid + " " + command.kind() + " \"" + v + "\"");
                break;
            }
            // output relation ZO11[Map<Many, string>]
            case flatbufTestRelation.ZO11: {
                @SuppressWarnings("unchecked")
                Map<ManyReader, String> v = (Map<ManyReader, String>)command.value();
                ArrayList<String> strings = new ArrayList<String>(v.size());
                for (Map.Entry<ManyReader, String> e: v.entrySet()) {
                    strings.add(printMany(e.getKey()) + "=>\"" + e.getValue() + "\"");
                }
                fb_file.println("From " + relid + " " + command.kind() + " {" + String.join(", ", strings) + "}");
                break;
            }
            // output relation ZO12[(string, bigint, Vec<bigint>, (bit<16>, Many))]
            case flatbufTestRelation.ZO12: {
                Tuple4__string__bigint__std_Vec_bigint____bit_16___Many_Reader v =
                    (Tuple4__string__bigint__std_Vec_bigint____bit_16___Many_Reader)command.value();
                fb_file.println("From " + relid + " " + command.kind() + " (\"" + v.a0() + "\", " + v.a1() +
                        ", " + v.a2() + ", ("  + v.a3().a0() + ", " + printMany(v.a3().a1()) + "))");
                break;
            }
            // output relation ZO13[Generic<Ref<tuple>, Many>]
            case flatbufTestRelation.ZO13: {
                Generic___bool__bit_8___string___ManyReader v =
                    (Generic___bool__bit_8___string___ManyReader)command.value();
                fb_file.println("From " + relid + " " + command.kind() + " Generic{\"" + v.f0() +
                        "\"," + printTuple(v.f1()) + "," + printMany(v.f2()) + "}");
                break;
            }
            // output relation ZO(d: bit<256>)
            case flatbufTestRelation.ZO: {
                ZOReader z = (ZOReader)command.value();
                fb_file.println("From " + relid + " " + command.kind() + " ZO{" + z.d() + "}");
                break;
            }
            case flatbufTestRelation.AAO: {
                AAOReader r = (AAOReader)command.value();
                fb_file.println("From " + relid + " " + command.kind() + " " + printCases("AAO", r.c()));
                break;
            }
            case flatbufTestRelation.ABO: {
                ABOReader r = (ABOReader)command.value();
                fb_file.println("From " + relid + " " + command.kind() + " " + printOr("ABO", r.c()));
                break;
            }
            case flatbufTestRelation.module_ACO: {
                module_ACOReader r = (module_ACOReader)command.value();
                fb_file.println("From " + relid + " " + command.kind() + " module_ACO{\"" + r.x() + "\"}");
                break;
            }
            default:
                fb_file.println("Unknown output relation " + relid);
                //throw new IllegalArgumentException("Unknown relation id " + relid);
        }

    }

    void update() throws DDlogException {
        flatbufTestUpdateBuilder builder = new flatbufTestUpdateBuilder();
        //builder.insert_AI("string");
        builder.insert_BI(true);
        builder.insert_CI((byte)8);
        builder.insert_DI((short)-5);
        builder.insert_DI((short)-1);
        builder.insert_DI((short)-2);
        builder.insert_DI((short)-3);
        builder.insert_DI((short)5);
        builder.insert_DI((short)1000);
        builder.insert_DI((short)Short.MAX_VALUE);
        builder.insert_DI((short)Short.MIN_VALUE);
        builder.insert_EI(BigInteger.ZERO.subtract(BigInteger.ONE));
        builder.insert_FI("string");
        builder.insert_GI((long)100);
        builder.insert_HI(new BigInteger("0ABACABA0ABACABA", 16));
        builder.insert_II((short)7);
        {
            Tuple3__bool__bit_8___stringWriter ji = builder.create_Tuple3__bool__bit_8___string(true, (byte)10, "string");
            builder.insert_JI(ji);
        }
        {
            Tuple3__bool__bit_8___stringWriter ki = builder.create_Tuple3__bool__bit_8___string(false, (byte)9, "text");
            builder.insert_KI(ki);
        }
        builder.insert_LI(true, (byte)-1, "something");
        builder.insert_L0I(false, (byte)-2, "else");
        {
            Boolean[] v = new Boolean[] {true, false, true};
            builder.insert_MI(Arrays.asList(v));
        }
        {
            ArrayList<Tuple3__bool__bit_8___stringWriter> vec = new ArrayList<Tuple3__bool__bit_8___stringWriter>(2);
            vec.add(builder.create_Tuple3__bool__bit_8___string(true, (byte)-1, "check"));
            vec.add(builder.create_Tuple3__bool__bit_8___string(false, (byte)1, "fails"));
            builder.insert_NI(vec);
        }
        {
            List<Boolean> l1 = Arrays.asList(new Boolean[] {false, false});
            List<Boolean> l2 = Arrays.asList(new Boolean[] {true, true});
            List<List<Boolean>> nest = new ArrayList<List<Boolean>>(2);
            nest.add(l1);
            nest.add(l2);
            builder.insert_OI(nest);
        }
        {
            List<Byte> pi = Arrays.asList(new Byte[]{ -2, 3, 2, 3 });
            builder.insert_PI1(pi);
        }
        {
            List<Short> pi = Arrays.asList(new Short[]{ 10000, 3, -2, 3 });
            builder.insert_PI2(pi);
        }
        {
            List<Integer> pi = Arrays.asList(new Integer[]{ 0xffffffff, 3, -2, 3 });
            builder.insert_PI3(pi);
        }
        {
            List<Long> pi = Arrays.asList(new Long[]{ 2L, 3L, 2L, 3L });
            builder.insert_PI4(pi);
        }
        {
            List<BigInteger> pi = Arrays.asList(new BigInteger[]{
                BigInteger.valueOf(0xffffffffffffffL),
                BigInteger.valueOf(3),
                BigInteger.valueOf(2),
                BigInteger.valueOf(3)
            });
            builder.insert_PI5(pi);
        }
        {
            Map<Long, String> map = new HashMap<Long, String>();
            map.put(Long.valueOf(2), "here");
            map.put(Long.valueOf(3), "there");
            builder.insert_QI(map);
        }
        builder.insert_RI(2);
        {
            CWriter c = builder.create_C("s");
            builder.insert_SI(c);
        }
        {
            std_Option__bit_32_Writer b = builder.create_std_Some__bit_32_(10);
            builder.insert_TI(b);
            std_Option__bit_32_Writer b1 = builder.create_std_None__bit_32_();
            builder.insert_TI(b1);
        }
        builder.insert_UI_A("a");
        builder.insert_UI_B(false);
        builder.insert_UI_D(builder.create_Tuple3__bool__bit_8___string(false, (byte)2, "zz"));
        {
            ManyWriter a = builder.create_A("aa");
            ManyWriter b = builder.create_B(false);
            ManyWriter d = builder.create_D(builder.create_Tuple3__bool__bit_8___string(false, (byte)2, "string"));
            builder.insert_VI(false, a);
            builder.insert_VI(true, b);
            builder.insert_VI(false, d);
        }
        {
            std_Option__ManyWriter om0 = builder.create_std_None__Many();
            builder.insert_WI(om0);
            std_Option__ManyWriter om1 = builder.create_std_Some__Many(builder.create_B(true));
            builder.insert_WI(om1);
        }
        {
            ManyWriter[] m = {
                builder.create_A("aa"),
                builder.create_B(false),
                builder.create_D(builder.create_Tuple3__bool__bit_8___string(false, (byte)2, "string"))
            };
            builder.insert_XI(Arrays.asList(m));
        }
        {
            std_Option___bool__bit_8___string_Writer[] v = {
                builder.create_std_Some___bool__bit_8___string_(
                    builder.create_Tuple3__bool__bit_8___string(false, (byte)-1, "")),
                builder.create_std_Some___bool__bit_8___string_(
                    builder.create_Tuple3__bool__bit_8___string(true, (byte)-2, "!")),
                builder.create_std_None___bool__bit_8___string_()
            };
            builder.insert_YI(Arrays.asList(v));
        }
        builder.insert_ZI0("Hello, world!");
        builder.insert_ZI0("Привіт!");
        builder.insert_ZI1(true);
        builder.insert_ZI1(false);
        builder.insert_ZI2((long)0);
        builder.insert_ZI2((long)1000);
        builder.insert_ZI3_A("It's all Greek to me:  Α α, Β β, Γ γ, Δ δ, Ε ε, Ζ ζ, Η η, Θ θ, Ι ι, Κ κ, Λ λ, Μ μ, Ν ν, Ξ ξ, Ο ο, Π π, Ρ ρ, Σ σ/ς, Τ τ, Υ υ, Φ φ, Χ χ, Ψ ψ, Ω ω.");
        {
            ArrayList<String> strings = new ArrayList<String>();
            strings.add("Foo\n");
            strings.add("\tbar");
            builder.insert_ZI4(strings);
        }
        {
            Map<String, ManyWriter> map = new HashMap<String, ManyWriter>();
            map.put("key1", builder.create_B(false));
            map.put("key2", builder.create_A("val2"));
            builder.insert_ZI5(map);
        }
        builder.insert_ZI6_std_Some("ZI6");
        builder.insert_ZI6_std_None();
        builder.insert_ZI7("♛");
        builder.insert_ZI7("ZI7");
        builder.insert_ZI8(100);
        builder.insert_ZI9(100);
        builder.insert_ZI10("Ref<IString>");
        {
            Map<ManyWriter, String> map = new HashMap<ManyWriter, String>();
            //map.put(builder.create_B(false), "v1");
            // Cannot add more than one record, since the map is printed in
            // non-deterministic order, so the diff fails.
            map.put(builder.create_A("val2"), "v2");
            builder.insert_ZI11(map);
        }
        {
            ArrayList<BigInteger> ints = new ArrayList<BigInteger>();
            ints.add(BigInteger.valueOf(0));
            ints.add(BigInteger.valueOf(0));
            ints.add(BigInteger.valueOf(1));
            builder.insert_ZI12(
                    "ZI12",
                    BigInteger.valueOf(1000000),
                    ints,
                    builder.create_Tuple2__bit_16___Many(0x10,
                        builder.create_D(builder.create_Tuple3__bool__bit_8___string(false, (byte)2, "string"))));
        }
        {
            ArrayList<BigInteger> ints = new ArrayList<BigInteger>();
            ints.add(BigInteger.valueOf(0));
            ints.add(BigInteger.valueOf(0));
            ints.add(BigInteger.valueOf(1));
            builder.insert_ZI13("ZI13", builder.create_Tuple3__bool__bit_8___string(false, (byte)2, "string"),
                    builder.create_A("ZI13"));
        }
        {
            BigInteger b = new BigInteger("01234566788901239813761283");
            builder.insert_ZI(b);
        }
        {
            Cases__string__signed_32_Writer w1 = builder.create_First__string__signed_32_("string");
            Cases__string__signed_32_Writer w2 = builder.create_Second__string__signed_32_(5);
            builder.insert_AAI(w1);
            builder.insert_AAI(w2);
        }
        {
            F__stringWriter f = builder.create_F__string("Or_string");
            Or__string__signed_32_Writer w1 = builder.create_OrFirst__string__signed_32_(f);
            S__signed_32_Writer s = builder.create_S__signed_32_(22);
            Or__string__signed_32_Writer w2 = builder.create_OrSecond__string__signed_32_(s);
            builder.insert_ABI(w1);
            builder.insert_ABI(w2);
        }
        {
            builder.insert_module_ACI("aci");
        }
        builder.applyUpdates(this.api);
        try {
            builder.applyUpdates(this.api);
            assert false: "Reusing UpdateBuilder should throw an exception.";
        } catch (IllegalStateException e) {}
    }

    void clear() throws DDlogException {
        this.api.clearRelation(flatbufTestRelation.BI);
        this.api.clearRelation(flatbufTestRelation.CI);
        this.api.clearRelation(flatbufTestRelation.DI);
        this.api.clearRelation(flatbufTestRelation.EI);
        this.api.clearRelation(flatbufTestRelation.FI);
        this.api.clearRelation(flatbufTestRelation.GI);
        this.api.clearRelation(flatbufTestRelation.HI);
        this.api.clearRelation(flatbufTestRelation.II);
        this.api.clearRelation(flatbufTestRelation.JI);
        this.api.clearRelation(flatbufTestRelation.KI);
        this.api.clearRelation(flatbufTestRelation.LI);
        this.api.clearRelation(flatbufTestRelation.L0I);
        this.api.clearRelation(flatbufTestRelation.MI);
        this.api.clearRelation(flatbufTestRelation.NI);
        this.api.clearRelation(flatbufTestRelation.OI);
        this.api.clearRelation(flatbufTestRelation.PI1);
        this.api.clearRelation(flatbufTestRelation.PI2);
        this.api.clearRelation(flatbufTestRelation.PI3);
        this.api.clearRelation(flatbufTestRelation.PI4);
        this.api.clearRelation(flatbufTestRelation.PI5);
        this.api.clearRelation(flatbufTestRelation.QI);
        this.api.clearRelation(flatbufTestRelation.RI);
        this.api.clearRelation(flatbufTestRelation.SI);
        this.api.clearRelation(flatbufTestRelation.TI);
        this.api.clearRelation(flatbufTestRelation.UI);
        this.api.clearRelation(flatbufTestRelation.VI);
        this.api.clearRelation(flatbufTestRelation.WI);
        this.api.clearRelation(flatbufTestRelation.XI);
        this.api.clearRelation(flatbufTestRelation.YI);
        this.api.clearRelation(flatbufTestRelation.ZI0);
        this.api.clearRelation(flatbufTestRelation.ZI1);
        this.api.clearRelation(flatbufTestRelation.ZI2);
        this.api.clearRelation(flatbufTestRelation.ZI3);
        this.api.clearRelation(flatbufTestRelation.ZI4);
        this.api.clearRelation(flatbufTestRelation.ZI5);
        this.api.clearRelation(flatbufTestRelation.ZI6);
        this.api.clearRelation(flatbufTestRelation.ZI7);
        this.api.clearRelation(flatbufTestRelation.ZI8);
        this.api.clearRelation(flatbufTestRelation.ZI9);
        this.api.clearRelation(flatbufTestRelation.ZI10);
        this.api.clearRelation(flatbufTestRelation.ZI11);
        this.api.clearRelation(flatbufTestRelation.ZI12);
        this.api.clearRelation(flatbufTestRelation.ZI13);
        this.api.clearRelation(flatbufTestRelation.ZI);
        this.api.clearRelation(flatbufTestRelation.AAI);
        this.api.clearRelation(flatbufTestRelation.ABI);
        this.api.clearRelation(flatbufTestRelation.module_ACI);
    }

    void run() throws IOException, DDlogException {
        /* DDlogRecord-based coommit */
        this.api.transactionStart();
        this.update();
        this.api.transactionCommitDumpChanges(r -> {
            try {
                this.onRecCommit(r);
            } catch (IOException e) {
                throw new UncheckedIOException(e);
            }
        });
        this.rec_file.close();

        /* Clear all input relations */
        this.api.transactionStart();
        this.clear();
        this.api.transactionCommit();

        /* FlatBuffers-based coommit */
        this.api.transactionStart();
        this.update();
        flatbufTestUpdateParser.transactionCommitDumpChanges(this.api, r -> {
            try {
                this.onFBCommit(r);
            } catch (IOException e) {
                throw new UncheckedIOException(e);
            }
        });
        this.fb_file.close();
    }

    public static void main(String[] args) throws IOException, DDlogException {
        Test test = new Test();
        test.run();
    }
}
