// A simple test for multiple DDlog programs communicating
// with each other. Each program is in a file under ../lr/

import lr.left as l
import lr.right as r
import lr.up as u
import lr.down as d

// The tables are connected as follows, where the output
// of the RHS table is the input of the LHS table

// r.Up   :- u.Right
// r.Down :- d.Right
// u.Left :- l.Up
// d.Left :- l.Down

//     u
//     |
// l -< >- r
//     |
//     d
