import foolib::lib
import foolib::ns1::m1 as m1
import foolib::ns1::m2 as m2
import redist
// Make sure we can compile streaming code that lives in a module.
import streams

input relation Rmain(f1: Tlib, f2: m1::T1)
output relation Rout(f1: bool, f2: bigint)

Rout(q, x) :- Rmain(Tlib{x}, m1::T1{y}), Rlib(m2::T2{z}), m1::R1(m2::T2{p}), m2::R2(q).

typedef Tmain = Tmain {f1: m1::T1}

function fmain(a1: Rlib): m1::R1 = m1::R1{m2::T2{0}}
