function strings(): () = {
    var str1 = "foo";
    var str2 = "bar";
    var ok = $"{str1+str2}";
    var err = $"{str1+str2";
    ()
}

//---

typedef Type1 = Cons1 | Cons2

function strings(): () = {
    var x: Type1 = Cons1;
    var err = $"{x}"; // don't know how to convert x to string
    ()
}

//---

function strings(): () = {
    var str2 = "bar";
    {var str1 = ""; ()};
    var err = $"{str2++str1}"; // str1 is not declared in this scope
    ()
}
