/* Test file for Datalog types */

// This is a one-line comment

/* This is a
   multi-line comment */

typedef t00 = int
typedef t01 = bool
typedef t02 = string
typedef t03 = bit<32>
typedef t04 = ( int )
typedef t05 = ( int, int )
typedef t06 = ( int, int, ( int ) )
typedef t07 = ()
typedef t08 = ( (), (), () )
typedef t09 = ( (int), (), (int) )
typedef t10 = ( int, bool, string, bit<32> )
typedef t11 = ( int, (bool, (string, (bit<32>))))
typedef t12 = t11
typedef t13 = ( t00, t01, t02, t03 )
typedef t14 = ( t04, t04 )
typedef t15 = Const15 { f: int }
typedef T16 = t15
typedef T17 = int
typedef t18 = Const18 { f0: int, f1: string, f2: t00 }
typedef t19 = C0 { f0: int }
            | C1 { f0: string }
            | C2 { f0: t00 }

