#!/bin/bash
# Shell script which generates a Java program from a DDlog program and compiles it

# Only run `stack install` if we are inside the DDlog source tree;
# otherwise expect `ddlog` to already be in `$PATH`
if test -f "../../stack.yaml"; then
    stack install
fi

if command clang -v 2>/dev/null; then
    export CC=clang
else
    export CC=gcc
fi

case $(uname -s) in
    Darwin*)    SHLIBEXT=dylib; JDK_OS=darwin;;
    Linux*)     SHLIBEXT=so; JDK_OS=linux;;
    *)          echo "Unsupported OS"; exit 1
esac

# Compile a DDlog program and a Java program that uses it.
# Requires the flatbuf library to be installed and in the CLASSPATH
# the DDLFLAGS environment variable is passed as arguments to ddlog
function compile {
    local DLFILE=$1   # ddlog program that is being compiled
    local JAVAPROG=$2 # java test program that is being compiled
    local BUILD=$3    # one of "debug" or "release"

    if [ "x${BUILD}" != "xdebug" -a "x${BUILD}" != "xrelease" ]; then
        echo "Third argument of compile must be 'debug' or 'release', not ${BUILD}"
        exit 1
    fi

    local DLPROG=$(basename ${DLFILE} .dl)
    local DLDIR=$(dirname ${DLFILE})
    if [ "x${DLDIR}" == "x" ]; then
        DLDIR="."
    fi

    CLASSPATH=$(pwd)/${DLDIR}/${DLPROG}_ddlog/flatbuf/java:$(pwd)/../ddlogapi.jar:..:.:$CLASSPATH
    # Compile the DDlog program
    ddlog ${DDLFLAGS} -i ${DLFILE} -L../../lib -j
    # Compile the generated rust program; generates ${DLDIR}/${DLPROG}_ddlog/target/${BUILD}/lib${DLPROG}_ddlog.a
    pushd ${DLDIR}/${DLPROG}_ddlog
    if [ "x${BUILD}" == "xrelease" ]; then
        cargo build --features=flatbuf --release
    else
        cargo build --features=flatbuf
    fi
    popd
    # Build the Java library with the DDlog API
    make -C ..
    # Build the generated Java classes for serialization (generated by flatbuf)
    (cd ${DLDIR}/${DLPROG}_ddlog/flatbuf/java && javac $(ls ddlog/__${DLPROG}/*.java) && javac $(ls ddlog/${DLPROG}/*.java))

    # Compile Java program
    javac -encoding utf8 -Xlint:unchecked ${JAVAPROG}
    # Create a shared library containing all the native code: ddlogapi.c, ${DLPROG}_ddlog.a
    ${CC} -std=gnu11 -shared -fPIC -I${JAVA_HOME}/include -I${JAVA_HOME}/include/${JDK_OS} -I${DLDIR}/${DLPROG}_ddlog -I../../lib ../ddlogapi.c -L${DLDIR}/${DLPROG}_ddlog/target/${BUILD}/ -l${DLPROG}_ddlog -o libddlogapi.${SHLIBEXT}
}

function cleanup {
    rm -rf ./*.class libddlogapi.${SHLIBEXT}
}
