typedef integer      = bit<64>
typedef uuid         = bit<128>

typedef uuid_or_string_t = Either<uuid, string>

function extract_uuid (id: uuid_or_string_t): uuid = {
    match (id) {
        Left{uuid} -> uuid,
        _ -> 0
    }
}

extern function uuid2str(id: uuid): string

extern function set_extract_uuids(ids: Set<uuid_or_string_t>): Set<uuid>
extern function map_extract_val_uuids(ids: Map<'K, uuid_or_string_t>): Map<'K, uuid>
