// args: build -Z dump-ast
// TODO: Make a better ast debugging format
// expected stdout:
// [
//     Declaration {
//         attributes: [],
//         kind: Relation(
//             Relation {
//                 kind: Internal,
//                 name: Ident {
//                     ident: "InternalRelation",
//                     kind: Uppercase,
//                 },
//                 args: [],
//             },
//         ),
//     },
//     Declaration {
//         attributes: [],
//         kind: Relation(
//             Relation {
//                 kind: Input,
//                 name: Ident {
//                     ident: "InputRelation",
//                     kind: Uppercase,
//                 },
//                 args: [],
//             },
//         ),
//     },
//     Declaration {
//         attributes: [],
//         kind: Relation(
//             Relation {
//                 kind: Output,
//                 name: Ident {
//                     ident: "OutputRelation",
//                     kind: Uppercase,
//                 },
//                 args: [],
//             },
//         ),
//     },
//     Declaration {
//         attributes: [],
//         kind: Relation(
//             Relation {
//                 kind: Internal,
//                 name: Ident {
//                     ident: "Test",
//                     kind: Uppercase,
//                 },
//                 args: [
//                     (
//                         Ident {
//                             ident: "foo",
//                             kind: Lowercase,
//                         },
//                         Bool,
//                     ),
//                 ],
//             },
//         ),
//     },
//     Declaration {
//         attributes: [],
//         kind: Relation(
//             Relation {
//                 kind: Output,
//                 name: Ident {
//                     ident: "Test",
//                     kind: Uppercase,
//                 },
//                 args: [
//                     (
//                         Ident {
//                             ident: "foo",
//                             kind: Lowercase,
//                         },
//                         String,
//                     ),
//                     (
//                         Ident {
//                             ident: "_bar",
//                             kind: Lowercase,
//                         },
//                         Bool,
//                     ),
//                 ],
//             },
//         ),
//     },
//     Declaration {
//         attributes: [],
//         kind: Relation(
//             Relation {
//                 kind: Output,
//                 name: Ident {
//                     ident: "Test",
//                     kind: Uppercase,
//                 },
//                 args: [
//                     (
//                         Ident {
//                             ident: "foo",
//                             kind: Lowercase,
//                         },
//                         String,
//                     ),
//                     (
//                         Ident {
//                             ident: "_bar",
//                             kind: Lowercase,
//                         },
//                         Bool,
//                     ),
//                 ],
//             },
//         ),
//     },
//     Declaration {
//         attributes: [
//             Attribute {
//                 ident: Ident {
//                     ident: "something",
//                     kind: Lowercase,
//                 },
//                 value: Some(
//                     Expr {
//                         kind: Literal(
//                             Int(
//                                 10,
//                             ),
//                         ),
//                     },
//                 ),
//             },
//             Attribute {
//                 ident: Ident {
//                     ident: "something_else",
//                     kind: Lowercase,
//                 },
//                 value: None,
//             },
//         ],
//         kind: Relation(
//             Relation {
//                 kind: Internal,
//                 name: Ident {
//                     ident: "RelationWithAttributes",
//                     kind: Uppercase,
//                 },
//                 args: [],
//             },
//         ),
//     },
//     Declaration {
//         attributes: [],
//         kind: Relation(
//             Relation {
//                 kind: Internal,
//                 name: Ident {
//                     ident: "ClausedRelation",
//                     kind: Uppercase,
//                 },
//                 args: [
//                     (
//                         Ident {
//                             ident: "boolean",
//                             kind: Lowercase,
//                         },
//                         Bool,
//                     ),
//                 ],
//             },
//         ),
//     },
//     Declaration {
//         attributes: [],
//         kind: Rule(
//             Rule {
//                 head: [
//                     RuleHead {
//                         relation: Ident {
//                             ident: "ClausedRelation",
//                             kind: Uppercase,
//                         },
//                         fields: [
//                             Expr {
//                                 kind: Ident(
//                                     Ident {
//                                         ident: "boolean",
//                                         kind: Lowercase,
//                                     },
//                                 ),
//                             },
//                         ],
//                     },
//                 ],
//                 clauses: [
//                     Expr(
//                         Expr {
//                             kind: Literal(
//                                 Bool(
//                                     true,
//                                 ),
//                             ),
//                         },
//                     ),
//                 ],
//             },
//         ),
//     },
// ]

relation InternalRelation()

input relation InputRelation()

output relation OutputRelation()

relation Test(foo: bool)

output relation Test(foo: string, _bar: bool)

output relation Test(foo: string, _bar: bool,)

#[something = 10]
#[something_else]
relation RelationWithAttributes()

relation ClausedRelation(boolean: bool)
ClausedRelation(boolean) :- true.
