// args: build -Z dump-ast
// TODO: Make a better ast debugging format
// expected stdout:
// [
//     Declaration {
//         attributes: [],
//         kind: Relation(
//             Relation {
//                 kind: Internal,
//                 name: Ident("InternalRelation"),
//                 args: [],
//             },
//         ),
//     },
//     Declaration {
//         attributes: [],
//         kind: Relation(
//             Relation {
//                 kind: Input,
//                 name: Ident("InputRelation"),
//                 args: [],
//             },
//         ),
//     },
//     Declaration {
//         attributes: [],
//         kind: Relation(
//             Relation {
//                 kind: Output,
//                 name: Ident("OutputRelation"),
//                 args: [],
//             },
//         ),
//     },
//     Declaration {
//         attributes: [],
//         kind: Relation(
//             Relation {
//                 kind: Internal,
//                 name: Ident("Test"),
//                 args: [
//                     (
//                         Ident("foo"),
//                         Bool,
//                     ),
//                 ],
//             },
//         ),
//     },
//     Declaration {
//         attributes: [],
//         kind: Relation(
//             Relation {
//                 kind: Output,
//                 name: Ident("Test2"),
//                 args: [
//                     (
//                         Ident("foo"),
//                         String,
//                     ),
//                     (
//                         Ident("_bar"),
//                         Bool,
//                     ),
//                 ],
//             },
//         ),
//     },
//     Declaration {
//         attributes: [],
//         kind: Relation(
//             Relation {
//                 kind: Output,
//                 name: Ident("Test3"),
//                 args: [
//                     (
//                         Ident("foo"),
//                         String,
//                     ),
//                     (
//                         Ident("_bar"),
//                         Bool,
//                     ),
//                 ],
//             },
//         ),
//     },
//     Declaration {
//         attributes: [
//             Attribute {
//                 ident: Ident("something"),
//                 value: Some(
//                     Expr {
//                         kind: Int(10),
//                     },
//                 ),
//             },
//             Attribute {
//                 ident: Ident("something_else"),
//                 value: None,
//             },
//         ],
//         kind: Relation(
//             Relation {
//                 kind: Internal,
//                 name: Ident("RelationWithAttributes"),
//                 args: [],
//             },
//         ),
//     },
//     Declaration {
//         attributes: [],
//         kind: Relation(
//             Relation {
//                 kind: Internal,
//                 name: Ident("ClausedRelation"),
//                 args: [
//                     (
//                         Ident("boolean"),
//                         Bool,
//                     ),
//                 ],
//             },
//         ),
//     },
//     Declaration {
//         attributes: [],
//         kind: Rule(
//             Rule {
//                 heads: [
//                     RuleHead {
//                         relation: Ident("ClausedRelation"),
//                         fields: [
//                             Expr {
//                                 kind: Ident("boolean"),
//                             },
//                         ],
//                     },
//                 ],
//                 clauses: [
//                     Relation {
//                         binding: None,
//                         relation: Ident("ClausedRelation"),
//                         fields: [
//                             Expr {
//                                 kind: Ident("boolean"),
//                             },
//                         ],
//                     },
//                 ],
//             },
//         ),
//     },
// ]

relation InternalRelation()

input relation InputRelation()

output relation OutputRelation()

relation Test(foo: bool)

output relation Test2(foo: string, _bar: bool)

output relation Test3(foo: string, _bar: bool,)

#[something = 10]
#[something_else]
relation RelationWithAttributes()

relation ClausedRelation(boolean: bool)
ClausedRelation(boolean) :- ClausedRelation(boolean).
