typedef integer      = bit<64>
typedef uuid         = bit<128>
typedef option_t<'A> = Some{x: 'A}
                     | None
typedef either_t<'A,'B> = Left{l: 'A}
                        | Right{r: 'B}
typedef uuid_or_string_t = either_t<uuid, string>

function extract_uuid (id: uuid_or_string_t): uuid = {
    match (id) {
        Left{uuid} -> uuid,
        _ -> 0
    }
}

extern function set_extract_uuids(ids: Set<uuid_or_string_t>): Set<uuid>
extern function map_extract_val_uuids(ids: Map<'K, uuid_or_string_t>): Map<'K, uuid>
