[package]
name = "tcp_channel"
version = "0.1.0"
authors = ["Remy Wang <remy.sucre@gmail.com>"]
edition = "2018"

[dependencies]
observe = {path = "../observe"}
serde_json = "1.0"
serde = "1.0"

[lib]
name = "tcp_channel"
path = "./lib.rs"
