[package]
name = "tcp_channel"
version = "0.1.0"
edition = "2018"

[dependencies]
bincode = "1.2"
libc = "0.2"
observe = {path = "../observe"}
serde = "1.0"

[lib]
name = "tcp_channel"
path = "lib.rs"
